{% set name = "dftd4-python" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/archive/v{{ version }}.tar.gz
  sha256: cba67cce1ebd194e844c582b3ebec250ba7d349894ee6e8052686e39c70131ce
  patches:
     - backport.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - python
    - cffi
    - pkgconfig
  host:
    - python
    - pip
    - dftd4
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('dftd4', max_pin='x.x') }}


test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase  # [python_impl == 'cpython']
  commands:
    - pytest --pyargs dftd4 -vv  # [python_impl == 'cpython']
    - pytest --pyargs dftd4 --ignore=dftd4/test_ase.py -vv  # [python_impl == 'pypy']

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Python API for the DFT-D4 project'
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.

extra:
  recipe-maintainers:
    - awvwgk
